import '../models/product.dart';

class MockData {
  static const List<Product> products = [
    Product(
      id: '1',
      title: 'Organic Lavender Oil',
      description: 'Premium organic lavender essential oil for relaxation.',
      price: 45.0,
      imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Wellness',
    ),
    Product(
      id: '2',
      title: 'Himalayan Bath Salts',
      description: 'Detoxifying bath salts sourced from the Himalayas.',
      price: 35.0,
      imageUrl: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Spa',
    ),
    Product(
      id: '3',
      title: 'Silk Sleep Mask',
      description: '100% pure mulberry silk sleep mask for deep rest.',
      price: 60.0,
      imageUrl: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Sleep',
    ),
    Product(
      id: '4',
      title: 'Premium Cork Yoga Mat',
      description: 'Eco-friendly, non-slip cork yoga mat for perfect grip during practice.',
      price: 85.0,
      imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Yoga',
    ),
    Product(
      id: '5',
      title: 'Ceremonial Grade Matcha',
      description: 'Pure organic matcha green tea powder imported from Uji, Japan.',
      price: 55.0,
      imageUrl: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Nutrition',
    ),
    Product(
      id: '6',
      title: 'Amethyst Crystal Bottle',
      description: 'Glass water bottle infused with natural amethyst crystals for positive energy.',
      price: 48.0,
      imageUrl: 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Accessories',
    ),
    Product(
      id: '7',
      title: 'Aromatherapy Diffuser',
      description: 'Ultrasonic ceramic essential oil diffuser with ambient LED lighting.',
      price: 120.0,
      imageUrl: 'https://images.unsplash.com/photo-1608528577891-eb055944f2e7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Wellness',
    ),
    Product(
      id: '8',
      title: 'Botanical Skincare Set',
      description: 'Complete daily regimen featuring wildcrafted botanical extracts.',
      price: 180.0,
      imageUrl: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Spa',
    ),
    Product(
      id: '9',
      title: 'Zafu Meditation Cushion',
      description: 'Ergonomic buckwheat-filled cushion for prolonged meditation sessions.',
      price: 75.0,
      imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Yoga',
    ),
    Product(
      id: '10',
      title: 'Palo Santo Bundles',
      description: 'Sustainably harvested palo santo sticks for energy clearing and smudging.',
      price: 24.0,
      imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Wellness',
    ),
    Product(
      id: '11',
      title: 'Organic Ashwagandha',
      description: 'Adaptogenic root powder to help manage stress and promote calm.',
      price: 32.0,
      imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Nutrition',
    ),
    Product(
      id: '12',
      title: 'Seamless Activewear Set',
      description: 'Breathable, flexible matching set designed for yoga and pilates.',
      price: 110.0,
      imageUrl: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Apparel',
    ),
    Product(
      id: '13',
      title: 'Rose Quartz Face Roller',
      description: 'Dual-ended crystal roller to reduce puffiness and improve circulation.',
      price: 45.0,
      imageUrl: 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Spa',
    ),
    Product(
      id: '14',
      title: 'Cashmere Throw Blanket',
      description: 'Ultra-soft, ethically sourced cashmere throw for deep relaxation.',
      price: 250.0,
      imageUrl: 'https://images.unsplash.com/photo-1542385151-efd9000785a0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Sleep',
    ),
    Product(
      id: '15',
      title: 'Bamboo Yoga Blocks',
      description: 'Set of two sustainable bamboo blocks to deepen your stretches.',
      price: 38.0,
      imageUrl: 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Yoga',
    ),
    Product(
      id: '16',
      title: 'Therapeutic Weighted Blanket',
      description: '15lb glass-bead weighted blanket designed to simulate a comforting hug.',
      price: 185.0,
      imageUrl: 'https://images.unsplash.com/photo-1542385151-efd9000785a0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Sleep',
    ),
    Product(
      id: '17',
      title: 'Tibetan Sound Bowl',
      description: 'Hand-hammered singing bowl set with mallet for sound healing sessions.',
      price: 95.0,
      imageUrl: 'https://images.unsplash.com/photo-1599839619722-39751411ea63?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Wellness',
    ),
    Product(
      id: '18',
      title: 'Superfood Green Powder',
      description: 'Daily detoxifying blend of spirulina, chlorella, and wheatgrass.',
      price: 65.0,
      imageUrl: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      category: 'Nutrition',
    ),
  ];
}
